let JokeDictionary = [
    'Kommt ein Mann zur Wahrsagerin und setzt sich vor die Kristallkugel. „Wie ich sehe, sind Sie Vater von zwei Kindern“, sagt die Wahrsagerin. „Das glauben SIE!“, erwidert er. „Ich bin Vater von drei Kindern.“ Die Wahrsagerin lächelt und antwortet: „Das glauben SIE!“',
    'Sagt ein Mann zu seinem Freund: „Meine Frau macht eine dreiwöchige Diät.“ „Und wie viel hat sie schon verloren?“ „Zwei Wochen.“',
    'Nach einer schnellen Verfolgungsjagd stoppt die Polizei Vlad. „So viel Spaß hatte ich den ganzen Tag nicht“, sagt der Polizist. „Wenn Sie eine gute Entschuldigung haben, lassen wir das mit dem Strafzettel.“ „Vor drei Wochen hat mich meine Frau wegen eines Polizisten verlassen“, erklärt Vlad. „Und als ich Ihr Auto kommen sah, fürchtete ich, Sie wollten sie zurückbringen.“',
    'Ein Starlet sitzt während eines Langstreckenfluges neben einem Rechtsanwalt. Sie will unbedingt ihren Schönheitsschlaf halten, doch der Rechtsanwalt hält sie vom Schlafen ab. „Lassen Sie uns ein Spiel mit Fragen zum Allgemeinwissen spielen“, schlägt er vor. Das Starlet ignoriert ihn. „Wir machen es ein bisschen interessanter“, sagt er. „Wenn ich eine falsche Antwort gebe, zahle ich Ihnen 50 Dollar. Antworten Sie falsch, schulden Sie mir fünf Dollar.“ Sie ist einverstanden. Der Anwalt fängt an. „Wie groß ist die Entfernung zwischen Erde und Mond?“ Das Starlet gibt dem Rechtsanwalt fünf Dollar. Dann ist sie dran. „Was geht den Berg auf drei Beinen hoch und kommt auf vier Beinen runter?“ Der Rechtsanwalt hat nicht die leiseste Ahnung. Er sucht im Internet, blättert durch seine Taschenenzyklopädie und schickt jedem Wissenschaftler in seinem Adressbuch eine SMS. Ohne Erfolg. Stunden später weckt er das Starlet, gibt ihr 50 Dollar und fragt: „Also, was ist es?“ Ohne ein Wort gibt sie ihm fünf Dollar, dreht sich um und schläft weiter.',
    'Ein Geschäftsmann besucht seinen chinesischen Freund im Krankenhaus. „Chin yu yan, chin yu yan …“, flüstert der Kranke mit schwacher Stimme. Der Geschäftsmann möchte ihm gern helfen, spricht aber kein Chinesisch. „Chin yu yan, chin yu yan!“, wiederholt der Patient. Kurz darauf ist er tot. Wenige Monate später ist der Mann auf Geschäftsreise in Schanghai, wo er lernt, was „chin yu yan“ bedeutet: „Geh von meinem Sauerstoffschlauch runter.“',
    'Ein hochbetagtes Ehepaar geht in einen Schnellimbiss, wo sich beide einen Hamburger und eine Portion Pommes frites gerecht aufteilen. Ein Lkw-Fahrer hat Mitleid mit ihnen und bietet an, der Frau eine eigene Mahlzeit zu spendieren. „Nein, danke“, sagt der Ehemann.',
    '„Wir teilen alles.“ Der Lkw-Fahrer bietet der Frau erneut eine Mahlzeit an, weil sie noch keinen Bissen gegessen hat.„Sie wird noch essen“, versichert ihm der Ehemann. „Wir teilen alles.“ „Und warum essen Sie dann noch nicht?“, fragt der Lkw-Fahrer die Frau. Darauf sie genervt: „Weil ich auf die Zähne warte!“',
    'Ein katholischer Priester, ein protestantischer Pfarrer und ein jüdischer Rabbi wollen herausfinden, wer von ihnen der beste Seelsorger ist. Alle drei gehen in den Wald, suchen einen Bären und versuchen ihn zu bekehren. Danach treffen sie sich wieder. Der Priester fängt an: „Als ich den Bären gefunden hatte, las ich ihm aus dem Katechismus vor und besprengte ihn mit Weihwasser. Nächste Woche feiert er Erste Kommunion.“ „Ich fand einen Bären am Fluss“, sagt der Pfarrer, „und predigte ihm Gottes Wort. Der Bär war so fasziniert, dass er in die Taufe einwilligte.“ Die beiden schauen hinunter auf den Rabbi, der mit einem Ganzkörpergips auf einer Bahre liegt. „Im Nachhinein betrachtet“, sagt der, „hätte ich vielleicht nicht mit der Beschneidung anfangen sollen.“',
    'Die Indianer in einem abgelegenen Reservat gehen zu ihrem neuen Häuptling und fragen, wie kalt der nächste Winter wird. Da er die geheimen Künste seiner Vorfahren nie gelernt hat, befiehlt er seinen Brüdern, Feuerholz zu sammeln, ruft aber auch den Wetterdienst an und fragt: „Wie kalt wird der Winter?“. „Sehr kalt“, lautet die Antwort. Der Häuptling kehrt zurück zu seinen Stammesbrüdern und trägt ihnen auf, mehr Feuerholz zu sammeln. Eine Woche später ruft er wieder an: „Sind Sie sicher, dass der Winter sehr kalt wird?“. „Vollkommen sicher.“ Der Häuptling befiehlt seinen Stammesbrüdern, noch mehr Feuerholz zu sammeln. Eine Woche später ruft er noch einmal an. „Sind Sie immer noch sicher?“ „Ja, es wird der kälteste Winter seit Menschengedenken“. „Woher wissen Sie das so genau?“ „Weil die Indianer wie verrückt Feuerholz sammeln!“',
    'Wegen der Rezession wird, um Strom zu sparen, das Licht am Ende des Tunnels abgeschaltet. Unterzeichnet: Gott.',
    'Zur Feier ihres 30. Hochzeitstages planen Hannu und seine Frau eine Reise in das Hotel, in dem sie einst ihre Flitterwochen verbracht haben. Alles soll perfekt sein. Hannu fährt einen Tag früher, um alles vorzubereiten. Nachts schreibt er eine E-Mail an seine Frau, gibt jedoch eine falsche Adresse ein, und die Nachricht landet stattdessen bei der Witwe eines kürzlich verstorbenen Pfarrers. Am nächsten Morgen findet der Sohn der Witwe seine Mutter ohnmächtig vor ihrem Computer. Dort steht: „Meine herzallerliebste Frau, ich bin gerade eingetroffen. Alles ist für deine Ankunft morgen vorbereitet. Ich hoffe, deine Reise wird so angenehm wie meine. P.S.: Es ist sehr heiß hier!“',
    'Ein Einwohner aus Stockholm fährt zur Entenjagd aufs Land. Als er eine Ente sieht, zielt er und schießt. Doch der Vogel fällt auf den Hof eines Bauern, und der rückt die Beute nicht heraus. „Das ist mein Vogel“, besteht der Städter auf seinem Recht. Der Bauer schlägt vor, den Streit, wie auf dem Land üblich, mit einem Tritt in den Unterleib bezulegen. „Wer weniger schreit, kriegt den Vogel.“ Der Städter ist einverstanden. Der Bauer holt aus und landet einen gewaltigen Tritt in den Weichteilen des Mannes. Der bricht zusammen und bleibt 20 Minuten am Boden liegen. Als er wieder aufstehen kann, keucht er: „Okay, jetzt bin ich dran.“ „Nee“, sagt der Bauer im Weggehen. „Hier, nehmen Sie die Ente.'
]
const generateRandomNumber = () => {
    return Math.floor(Math.random() * 12 + 1)
}
console.log(JokeDictionary[generateRandomNumber()]);